
function countryName(){


frmProfile.lstboxStates.masterData=[
	["AL", "Alabama"],
	["AK", "Alaska"],
	["AS", "American Samoa"],
	["AZ", "Arizona"],
	["AR", "Arkansas"],
	["CA", "California"],
	["CO", "Colorado"],
	["CT", "Connecticut"],
	["DE", "Delaware"],
	["DC", "District Of Columbia"],
	["FM", "Federated States Of Micronesia"],
	["FL", "Florida"],
	["GA", "Georgia"],
	["GU", "Guam"],
	["HI", "Hawaii"],
	["ID", "Idaho"],
	["IL", "Illinois"],
	["IN", "Indiana"],
	["IA", "Iowa"],
	["KS", "Kansas"],
	["KY", "Kentucky"],
	["LA", "Louisiana"],
	["ME", "Maine"],
	["MH", "Marshall Islands"],
	["MD", "Maryland"],
	["MA", "Massachusetts"],
	["MI", "Michigan"],
	["MN", "Minnesota"],
	["MS", "Mississippi"],
	["MO", "Missouri"],
	["MT", "Montana"],
	["NE", "Nebraska"],
	["NV", "Nevada"],
	["NH", "New Hampshire"],
	["NJ", "New Jersey"],
	["NM", "New Mexico"],
	["NY", "New York"],
	["NC", "North Carolina"],
	["ND", "North Dakota"],
	["MP", "Northern Mariana Islands"],
	["OH", "Ohio"],
	["OK", "Oklahoma"],
	["OR", "Oregon"],
	["PW", "Palau"],
	["PA", "Pennsylvania"],
	["PR", "Puerto Rico"],
	["RI", "Rhode Island"],
	["SC", "South Carolina"],
	["SD", "South Dakota"],
	["TN", "Tennessee"],
	["TX", "Texas"],
	["UT", "Utah"],
	["VT", "Vermont"],
	["VI", "Virgin Islands"],
	["VA", "Virginia"],
	["WA", "Washington"],
	["WV", "West Virginia"],
	["WI", "Wisconsin"],
	["WY", "Wyoming"]
];



frmProfile.listbox5316540885527.masterData=[
	["Afghanistan", "Afghanistan"],
	["Albania", "Albania"],
	["Algeria", "Algeria"],
	["American Samoa", "American Samoa"],
	["Andorra", "Andorra"],
	["Angola", "Angola"],
	["Anguilla", "Anguilla"],
	["Antarctica", "Antarctica"],
	["Antigua &amp; Barbuda", "Antigua &amp; Barbuda"],
	["Argentina", "Argentina"],
	["Armenia", "Armenia"],
	["Aruba", "Aruba"],
	["Australia", "Australia"],
	["Austria", "Austria"],
	["Azerbaijan", "Azerbaijan"],
	["Bahamas", "Bahamas"],
	["Bahrain", "Bahrain"],
	["Bangladesh", "Bangladesh"],
	["Barbados", "Barbados"],
	["Belarus", "Belarus"],
	["Belgium", "Belgium"],
	["Belize", "Belize"],
	["Benin", "Benin"],
	["Bermuda", "Bermuda"],
	["Bhutan", "Bhutan"],
	["Bolivia", "Bolivia"],
	["Bosnia &amp; Herzegovina", "Bosnia &amp; Herzegovina"],
	["Botswana", "Botswana"],
	["Brazil", "Brazil"],
	["British Indian Ocean Territory", "British Indian Ocean Territory"],
	["British Virgin Islands", "British Virgin Islands"],
	["Brunei", "Brunei"],
	["Bulgaria", "Bulgaria"],
	["Burkina Faso", "Burkina Faso"],
	["Burundi", "Burundi"],
	["Cambodia", "Cambodia"],
	["Cameroon", "Cameroon"],
	["Canada", "Canada"],
	["Cape Verde", "Cape Verde"],
	["Cayman Islands", "Cayman Islands"],
	["Central African Republic", "Central African Republic"],
	["Chad", "Chad"],
	["Chile", "Chile"],
	["China", "China"],
	["Christmas Island", "Christmas Island"],
	["Cocos Islands", "Cocos Islands"],
	["Colombia", "Colombia"],
	["Cook Islands", "Cook Islands"],
	["Costa Rica", "Costa Rica"],
	["Croatia", "Croatia"],
	["Cuba", "Cuba"],
	["Curacao", "Curacao"],
	["Cyprus", "Cyprus"],
	["Czech Republic", "Czech Republic"],
	["Democratic Republic of the Congo", "Democratic Republic of the Congo"],
	["Denmark", "Denmark"],
	["Djibouti", "Djibouti"],
	["Dominica", "Dominica"],
	["Dominican Republic", "Dominican Republic"],
	["East Timor", "East Timor"],
	["Ecuador", "Ecuador"],
	["Egypt", "Egypt"],
	["El Salvador", "El Salvador"],
	["Equatorial Guinea", "Equatorial Guinea"],
	["Eritrea", "Eritrea"],
	["Estonia", "Estonia"],
	["Ethiopia", "Ethiopia"],
	["Falkland Islands", "Falkland Islands"],
	["Faroe Islands", "Faroe Islands"],
	["Fiji", "Fiji"],
	["Finland", "Finland"],
	["France", "France"],
	["French Polynesia", "French Polynesia"],
	["Gabon", "Gabon"],
	["Gambia", "Gambia"],
	["Georgia", "Georgia"],
	["Germany", "Germany"],
	["Ghana", "Ghana"],
	["Gibraltar", "Gibraltar"],
	["Greece", "Greece"],
	["Greenland", "Greenland"],
	["Grenada", "Grenada"],
	["Guam", "Guam"],
	["Guatemala", "Guatemala"],
	["Guernsey", "Guernsey"],
	["Guinea", "Guinea"],
	["Guinea Bissau", "Guinea Bissau"],
	["Guyana", "Guyana"],
	["Haiti", "Haiti"],
	["Honduras", "Honduras"],
	["Hong Kong", "Hong Kong"],
	["Hungary", "Hungary"],
	["Iceland", "Iceland"],
	["India", "India"],
	["Indonesia", "Indonesia"],
	["Iran", "Iran"],
	["Iraq", "Iraq"],
	["Ireland", "Ireland"],
	["Isle of Man", "Isle of Man"],
	["Israel", "Israel"],
	["Italy", "Italy"],
	["Ivory Coast", "Ivory Coast"],
	["Jamaica", "Jamaica"],
	["Japan", "Japan"],
	["Jersey", "Jersey"],
	["Jordan", "Jordan"],
	["Kazakhstan", "Kazakhstan"],
	["Kenya", "Kenya"],
	["Kiribati", "Kiribati"],
	["Kosovo", "Kosovo"],
	["Kuwait", "Kuwait"],
	["Kyrgyzstan", "Kyrgyzstan"],
	["Laos", "Laos"],
	["Latvia", "Latvia"],
	["Lebanon", "Lebanon"],
	["Lesotho", "Lesotho"],
	["Liberia", "Liberia"],
	["Libya", "Libya"],
	["Liechtenstein", "Liechtenstein"],
	["Lithuania", "Lithuania"],
	["Luxembourg", "Luxembourg"],
	["Macau", "Macau"],
	["Macedonia", "Macedonia"],
	["Madagascar", "Madagascar"],
	["Malawi", "Malawi"],
	["Malaysia", "Malaysia"],
	["Maldives", "Maldives"],
	["Mali", "Mali"],
	["Malta", "Malta"],
	["Marshall Islands", "Marshall Islands"],
	["Mauritania", "Mauritania"],
	["Mauritius", "Mauritius"],
	["Mexico", "Mexico"],
	["Micronesia", "Micronesia"],
	["Moldova", "Moldova"],
	["Monaco", "Monaco"],
	["Mongolia", "Mongolia"],
	["Montenegro", "Montenegro"],
	["Montserrat", "Montserrat"],
	["Morocco", "Morocco"],
	["Mozambique", "Mozambique"],
	["Myanmar", "Myanmar"],
	["Namibia", "Namibia"],
	["Nepal", "Nepal"],
	["Netherlands", "Netherlands"],
	["Netherlands Antilles", "Netherlands Antilles"],
	["New Caledonia", "New Caledonia"],
	["New Zealand", "New Zealand"],
	["Nicaragua", "Nicaragua"],
	["Niger", "Niger"],
	["Nigeria", "Nigeria"],
	["Niue", "Niue"],
	["North Korea", "North Korea"],
	["Northern Mariana Islands", "Northern Mariana Islands"],
	["Norway", "Norway"],
	["Oman", "Oman"],
	["Pakistan", "Pakistan"],
	["Palau", "Palau"],
	["Palestine", "Palestine"],
	["Panama", "Panama"],
	["Papua New Guinea", "Papua New Guinea"],
	["Paraguay", "Paraguay"],
	["Peru", "Peru"],
	["Philippines", "Philippines"],
	["Pitcairn", "Pitcairn"],
	["Poland", "Poland"],
	["Portugal", "Portugal"],
	["Puerto Rico", "Puerto Rico"],
	["Qatar", "Qatar"],
	["Republic of the Congo", "Republic of the Congo"],
	["Reunion", "Reunion"],
	["Romania", "Romania"],
	["Russia", "Russia"],
	["Rwanda", "Rwanda"],
	["Saint Barthelemy", "Saint Barthelemy"],
	["Saint Helena", "Saint Helena"],
	["Saint Kitts and Nevis", "Saint Kitts and Nevis"],
	["Saint Lucia", "Saint Lucia"],
	["Saint Martin", "Saint Martin"],
	["Saint Pierre &amp; Miquelon", "Saint Pierre &amp; Miquelon"],
	["Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"],
	["Samoa", "Samoa"],
	["San Marino", "San Marino"],
	["Sao Tome and Principe", "Sao Tome and Principe"],
	["Saudi Arabia", "Saudi Arabia"],
	["Senegal", "Senegal"],
	["Serbia", "Serbia"],
	["Seychelles", "Seychelles"],
	["Sierra Leone", "Sierra Leone"],
	["Singapore", "Singapore"],
	["Sint Maarten", "Sint Maarten"],
	["Slovakia", "Slovakia"],
	["Slovenia", "Slovenia"],
	["Solomon Islands", "Solomon Islands"],
	["Somalia", "Somalia"],
	["South Africa", "South Africa"],
	["South Korea", "South Korea"],
	["South Sudan", "South Sudan"],
	["Spain", "Spain"],
	["Sri Lanka", "Sri Lanka"],
	["Sudan", "Sudan"],
	["Suriname", "Suriname"],
	["Svalbard and Jan Mayen", "Svalbard and Jan Mayen"],
	["Swaziland", "Swaziland"],
	["Sweden", "Sweden"],
	["Switzerland", "Switzerland"],
	["Syria", "Syria"],
	["Taiwan", "Taiwan"],
	["Tajikistan", "Tajikistan"],
	["Tanzania", "Tanzania"],
	["Thailand", "Thailand"],
	["Togo", "Togo"],
	["Tokelau", "Tokelau"],
	["Tonga", "Tonga"],
	["Trinidad &amp; Tobago", "Trinidad &amp; Tobago"],
	["Tunisia", "Tunisia"],
	["Turkey", "Turkey"],
	["Turkmenistan", "Turkmenistan"],
	["Turks &amp; Caicos Islands", "Turks &amp; Caicos Islands"],
	["Tuvalu", "Tuvalu"],
	["U.S. Virgin Islands", "U.S. Virgin Islands"],
	["Uganda", "Uganda"],
	["Ukraine", "Ukraine"],
	["United Arab Emirates", "United Arab Emirates"],
	["United Kingdom", "United Kingdom"],
	["United States", "United States"],
	["Uruguay", "Uruguay"],
	["Uzbekistan", "Uzbekistan"],
	["Vanuatu", "Vanuatu"],
	["Vatican", "Vatican"],
	["Venezuela", "Venezuela"],
	["Vietnam", "Vietnam"],
	["Wallis and Futuna", "Wallis and Futuna"],
	["Western Sahara", "Western Sahara"],
	["Yemen", "Yemen"],
	["Zambia", "Zambia"],
	["Zimbabwe", "Zimbabwe"]
];
}
